name: Full-year calendar
on:
  push:
    branches:
      - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses:
lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN}}
